version: "3.9"
services:
  redis:
    image: redis:alpine # Use a lightweight Redis image
    container_name: pokemon-redis
    ports:
      - "6379:6379" # Expose Redis on the default port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
